//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class cat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nails.cat", typeof(cat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airbrush.
        /// </summary>
        public static string Airbrush {
            get {
                return ResourceManager.GetString("Airbrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural.
        /// </summary>
        public static string Architectural {
            get {
                return ResourceManager.GetString("Architectural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletic.
        /// </summary>
        public static string Athletic {
            get {
                return ResourceManager.GetString("Athletic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath &amp; Body.
        /// </summary>
        public static string Bath_Body {
            get {
                return ResourceManager.GetString("Bath_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        public static string Beauty {
            get {
                return ResourceManager.GetString("Beauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Products.
        /// </summary>
        public static string Beauty_Products {
            get {
                return ResourceManager.GetString("Beauty_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Styles.
        /// </summary>
        public static string Beauty_Styles {
            get {
                return ResourceManager.GetString("Beauty_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrities.
        /// </summary>
        public static string Celebrities {
            get {
                return ResourceManager.GetString("Celebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Schemes.
        /// </summary>
        public static string Color_Schemes {
            get {
                return ResourceManager.GetString("Color_Schemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was super easy.
        /// </summary>
        public static string Comment_Ans_1 {
            get {
                return ResourceManager.GetString("Comment_Ans_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was average.
        /// </summary>
        public static string Comment_Ans_2 {
            get {
                return ResourceManager.GetString("Comment_Ans_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was very hard.
        /// </summary>
        public static string Comment_Ans_3 {
            get {
                return ResourceManager.GetString("Comment_Ans_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only a professional could this..
        /// </summary>
        public static string Comment_Ans_4 {
            get {
                return ResourceManager.GetString("Comment_Ans_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how helpful was this.
        /// </summary>
        public static string Comment_Ques {
            get {
                return ResourceManager.GetString("Comment_Ques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy.
        /// </summary>
        public static string Crazy {
            get {
                return ResourceManager.GetString("Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration Ideas.
        /// </summary>
        public static string Decoration_Ideas {
            get {
                return ResourceManager.GetString("Decoration_Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do It Now.
        /// </summary>
        public static string Do_It_Now {
            get {
                return ResourceManager.GetString("Do_It_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essentials.
        /// </summary>
        public static string Essentials {
            get {
                return ResourceManager.GetString("Essentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        public static string Exterior {
            get {
                return ResourceManager.GetString("Exterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Shadow.
        /// </summary>
        public static string Eye_Shadow {
            get {
                return ResourceManager.GetString("Eye_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        public static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion.
        /// </summary>
        public static string Fashion {
            get {
                return ResourceManager.GetString("Fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures.
        /// </summary>
        public static string Fixtures {
            get {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooring.
        /// </summary>
        public static string Flooring {
            get {
                return ResourceManager.GetString("Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragrances.
        /// </summary>
        public static string Fragrances {
            get {
                return ResourceManager.GetString("Fragrances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeStyle.
        /// </summary>
        public static string FreeStyle {
            get {
                return ResourceManager.GetString("FreeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitter.
        /// </summary>
        public static string Glitter {
            get {
                return ResourceManager.GetString("Glitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string Gradient {
            get {
                return ResourceManager.GetString("Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Accessories.
        /// </summary>
        public static string Hair_Accessories {
            get {
                return ResourceManager.GetString("Hair_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Care.
        /// </summary>
        public static string Hair_Care {
            get {
                return ResourceManager.GetString("Hair_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair - How To.
        /// </summary>
        public static string Hair_How_To {
            get {
                return ResourceManager.GetString("Hair_How_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Style.
        /// </summary>
        public static string Hair_Style {
            get {
                return ResourceManager.GetString("Hair_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hats.
        /// </summary>
        public static string Hats {
            get {
                return ResourceManager.GetString("Hats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobos.
        /// </summary>
        public static string Hobos {
            get {
                return ResourceManager.GetString("Hobos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a Pin Party.
        /// </summary>
        public static string Host_a_Pin_Party {
            get {
                return ResourceManager.GetString("Host_a_Pin_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-To.
        /// </summary>
        public static string How_To {
            get {
                return ResourceManager.GetString("How_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Gallery.
        /// </summary>
        public static string How_To_Gallery {
            get {
                return ResourceManager.GetString("How_To_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        public static string Interior {
            get {
                return ResourceManager.GetString("Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interiors.
        /// </summary>
        public static string Interiors {
            get {
                return ResourceManager.GetString("Interiors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackets.
        /// </summary>
        public static string Jackets {
            get {
                return ResourceManager.GetString("Jackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeans.
        /// </summary>
        public static string Jeans {
            get {
                return ResourceManager.GetString("Jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        public static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lip Stick.
        /// </summary>
        public static string Lip_Stick {
            get {
                return ResourceManager.GetString("Lip_Stick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make-Up.
        /// </summary>
        public static string Make_Up {
            get {
                return ResourceManager.GetString("Make_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manicure.
        /// </summary>
        public static string Manicure {
            get {
                return ResourceManager.GetString("Manicure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity.
        /// </summary>
        public static string Maternity {
            get {
                return ResourceManager.GetString("Maternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matte.
        /// </summary>
        public static string Matte {
            get {
                return ResourceManager.GetString("Matte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mens.
        /// </summary>
        public static string Mens {
            get {
                return ResourceManager.GetString("Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic.
        /// </summary>
        public static string Metallic {
            get {
                return ResourceManager.GetString("Metallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Followers.
        /// </summary>
        public static string Most_Followers {
            get {
                return ResourceManager.GetString("Most_Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Likes.
        /// </summary>
        public static string Most_Likes {
            get {
                return ResourceManager.GetString("Most_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Pins.
        /// </summary>
        public static string Most_Pins {
            get {
                return ResourceManager.GetString("Most_Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular Pins.
        /// </summary>
        public static string Most_Popular_Pins {
            get {
                return ResourceManager.GetString("Most_Popular_Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi (3+).
        /// </summary>
        public static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail Polish.
        /// </summary>
        public static string Nail_Polish {
            get {
                return ResourceManager.GetString("Nail_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nails.
        /// </summary>
        public static string Nails {
            get {
                return ResourceManager.GetString("Nails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string Other_Settings {
            get {
                return ResourceManager.GetString("Other_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Touches.
        /// </summary>
        public static string Other_Touches {
            get {
                return ResourceManager.GetString("Other_Touches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outerwear.
        /// </summary>
        public static string Outerwear {
            get {
                return ResourceManager.GetString("Outerwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit.
        /// </summary>
        public static string Outfit {
            get {
                return ResourceManager.GetString("Outfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants &amp; Shorts.
        /// </summary>
        public static string Pants_Shorts {
            get {
                return ResourceManager.GetString("Pants_Shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        public static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Tools.
        /// </summary>
        public static string Pattern_Tools {
            get {
                return ResourceManager.GetString("Pattern_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedicures.
        /// </summary>
        public static string Pedicures {
            get {
                return ResourceManager.GetString("Pedicures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumps.
        /// </summary>
        public static string Pumps {
            get {
                return ResourceManager.GetString("Pumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny.
        /// </summary>
        public static string Shiny {
            get {
                return ResourceManager.GetString("Shiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an invite to join PinPolish.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        public static string Stamp {
            get {
                return ResourceManager.GetString("Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stilleto.
        /// </summary>
        public static string Stilleto {
            get {
                return ResourceManager.GetString("Stilleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatoos.
        /// </summary>
        public static string Tatoos {
            get {
                return ResourceManager.GetString("Tatoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Experience.
        /// </summary>
        public static string The_Experience {
            get {
                return ResourceManager.GetString("The_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        public static string ThreeD {
            get {
                return ResourceManager.GetString("ThreeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toes.
        /// </summary>
        public static string Toes {
            get {
                return ResourceManager.GetString("Toes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Hundreds.
        /// </summary>
        public static string Top_Hundreds {
            get {
                return ResourceManager.GetString("Top_Hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tops.
        /// </summary>
        public static string Tops {
            get {
                return ResourceManager.GetString("Tops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totes.
        /// </summary>
        public static string Totes {
            get {
                return ResourceManager.GetString("Totes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string Trim {
            get {
                return ResourceManager.GetString("Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuxedos.
        /// </summary>
        public static string Tuxedos {
            get {
                return ResourceManager.GetString("Tuxedos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Tone.
        /// </summary>
        public static string Two_Tone {
            get {
                return ResourceManager.GetString("Two_Tone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With People.
        /// </summary>
        public static string With_People {
            get {
                return ResourceManager.GetString("With_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womens.
        /// </summary>
        public static string Womens {
            get {
                return ResourceManager.GetString("Womens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
