//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nails.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string Add_Comment {
            get {
                return ResourceManager.GetString("Add_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450 Sources, Fresh Daily, Original Sources - Pin On!.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Name cannot be blank!.
        /// </summary>
        public static string Board_Blank {
            get {
                return ResourceManager.GetString("Board_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Board.
        /// </summary>
        public static string Board_Create {
            get {
                return ResourceManager.GetString("Board_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to create a board first.
        /// </summary>
        public static string Board_First {
            get {
                return ResourceManager.GetString("Board_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Name.
        /// </summary>
        public static string Board_Name {
            get {
                return ResourceManager.GetString("Board_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board was created successfully.
        /// </summary>
        public static string Board_Success {
            get {
                return ResourceManager.GetString("Board_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board was updated successfully.
        /// </summary>
        public static string Board_Update_Msg {
            get {
                return ResourceManager.GetString("Board_Update_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Category from dropdown.
        /// </summary>
        public static string Cat_DD {
            get {
                return ResourceManager.GetString("Cat_DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Category.
        /// </summary>
        public static string Cat_Select {
            get {
                return ResourceManager.GetString("Cat_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国的.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Comment.
        /// </summary>
        public static string Comment_Enter {
            get {
                return ResourceManager.GetString("Comment_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a contributor\&apos;s Email address or Username and then click &quot;Add&quot;.
        /// </summary>
        public static string Contributor_Add {
            get {
                return ResourceManager.GetString("Contributor_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contributor is already added.
        /// </summary>
        public static string Contributor_Usr_Warn {
            get {
                return ResourceManager.GetString("Contributor_Usr_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot be the contributor to the board you have created.
        /// </summary>
        public static string Contributor_Warn {
            get {
                return ResourceManager.GetString("Contributor_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Board.
        /// </summary>
        public static string Create_Board {
            get {
                return ResourceManager.GetString("Create_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the board.This will remove all the images within the board.
        /// </summary>
        public static string Del_Board_Confirm {
            get {
                return ResourceManager.GetString("Del_Board_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Board.
        /// </summary>
        public static string Delete_Board {
            get {
                return ResourceManager.GetString("Delete_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Pin.
        /// </summary>
        public static string Delete_Pin {
            get {
                return ResourceManager.GetString("Delete_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 book for poor students.
        /// </summary>
        public static string Donate_Book {
            get {
                return ResourceManager.GetString("Donate_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Board.
        /// </summary>
        public static string Edit_Board {
            get {
                return ResourceManager.GetString("Edit_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pin.
        /// </summary>
        public static string Edit_Pin {
            get {
                return ResourceManager.GetString("Edit_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is not registered with our application.
        /// </summary>
        public static string Email_Not_Reg {
            get {
                return ResourceManager.GetString("Email_Not_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address has already been registered with our application.
        /// </summary>
        public static string Email_Registered {
            get {
                return ResourceManager.GetString("Email_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email OR User Name.
        /// </summary>
        public static string Email_UN {
            get {
                return ResourceManager.GetString("Email_UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Board Name.
        /// </summary>
        public static string Enter_Board_Name {
            get {
                return ResourceManager.GetString("Enter_Board_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Full Name.
        /// </summary>
        public static string Enter_Full_Name {
            get {
                return ResourceManager.GetString("Enter_Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Name.
        /// </summary>
        public static string Enter_User_Name {
            get {
                return ResourceManager.GetString("Enter_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a board with that name. Please use a different board name.
        /// </summary>
        public static string ErrSameBoardName {
            get {
                return ResourceManager.GetString("ErrSameBoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the fields in red.
        /// </summary>
        public static string Fields_Red {
            get {
                return ResourceManager.GetString("Fields_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed!!.
        /// </summary>
        public static string File_Fail {
            get {
                return ResourceManager.GetString("File_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Me.
        /// </summary>
        public static string Follow_Me {
            get {
                return ResourceManager.GetString("Follow_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        public static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followings.
        /// </summary>
        public static string Followings {
            get {
                return ResourceManager.GetString("Followings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_Pass {
            get {
                return ResourceManager.GetString("Forgot_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A free décor magazine!.
        /// </summary>
        public static string Get_Magazine {
            get {
                return ResourceManager.GetString("Get_Magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is SiteName?.
        /// </summary>
        public static string Help_1 {
            get {
                return ResourceManager.GetString("Help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Practices.
        /// </summary>
        public static string Help_2 {
            get {
                return ResourceManager.GetString("Help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Help_3 {
            get {
                return ResourceManager.GetString("Help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        public static string Help_5 {
            get {
                return ResourceManager.GetString("Help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    What is SiteName?&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    SiteName is a stream of images from over 450 curated sites. It is a simple and
        ///                    convenient way to find new content for your stylebook or pinboard.&lt;/p&gt;
        ///                &lt;p&gt;
        ///                    We started SiteName because we wanted an easier way to get new ideas onto our pinboards.
        ///                &lt;/p&gt;
        ///                &lt;p&gt;
        ///                    We simply wanted fresh content from original sources. S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_About {
            get {
                return ResourceManager.GetString("Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    COPYRIGHT&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    SiteName (&quot;SiteName&quot;) respects the intellectual property rights of others and expects its users to do the same. It is SiteName policy, in appropriate circumstances and at its discretion, to disable and/or terminate the accounts of users who repeatedly infringe or are repeatedly charged with infringing the copyrights or other intellectual property rights of others.&lt;/p&gt;
        ///                &lt;p&gt;
        ///                    In accordance wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_CopyRight {
            get {
                return ResourceManager.GetString("Help_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;What is SiteName?&lt;/h3&gt;
        ///&lt;p&gt; SiteName is a stream of images from over 450 curated sites. It is a simple and convenient
        ///    way to find new content for your stylebook or pinboard.&lt;/p&gt;
        ///&lt;p&gt; We started SiteName because we wanted an easier way to get new ideas onto our pinboards.&lt;/p&gt;
        ///&lt;p&gt; We simply wanted fresh content from original sources. So we built SiteName.&lt;/p&gt;
        ///&lt;p&gt; With SiteName you only browse unique images, filtered and sorted the way you want
        ///    them. We try to eliminate all duplicates to save y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Main {
            get {
                return ResourceManager.GetString("Help_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    PIN PRACTICES&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    We curate SiteName to make sure all the pins are well categorized and of high quality.But the people who use SiteName make it so much more special with their contributions.
        ///                &lt;/p&gt;
        ///                &lt;p&gt;
        ///                    We&apos;ve taken the collective input of SiteName users and have laid down these guidelines that will help us keep the SiteName community positive, useful and clean.
        ///                &lt;/p&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Pin_Practices {
            get {
                return ResourceManager.GetString("Help_Pin_Practices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    PRIVACY POLICY&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    SiteName ( &quot; SiteName &quot;,&quot; we &quot;, &quot;us&quot;, &quot;our&quot; provides a Website located at &lt;a href=&quot;http://pinjimu.com&quot;&gt; http://pinjimu.com &lt;/a&gt;for users of the Website ( &quot; Member(s)&quot;,
        ///                    &lt;br /&gt;
        ///                    &quot; User(s) &quot;, &quot; you &quot; ). This Privacy Policy explains our policies regarding information you provide and we collect and how we may use or disclose that information. We value your privacy and provide this Priv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Privacy {
            get {
                return ResourceManager.GetString("Help_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    TERMS OF USE&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    Please read carefully the following terms and conditions. These Terms govern your access to and use of the Site and Services and all Site Content (defined below), and constitute a binding legal agreement between you and SiteName.&lt;/p&gt;
        ///                &lt;h3&gt;
        ///                    Key Terms related to Content&lt;/h3&gt;
        ///                &lt;p&gt;
        ///                    &quot; Content &quot; means text, graphics, images, music, software, audio, video,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Term {
            get {
                return ResourceManager.GetString("Help_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdeaBoards.
        /// </summary>
        public static string IdeaBoards {
            get {
                return ResourceManager.GetString("IdeaBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile picture.
        /// </summary>
        public static string Image_1 {
            get {
                return ResourceManager.GetString("Image_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only Image files to upload (gif, jpg, jpeg, bmp, tiff, tif types only).
        /// </summary>
        public static string Image_Invalid {
            get {
                return ResourceManager.GetString("Image_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins has been Added Successfully.
        /// </summary>
        public static string Image_Success_Added {
            get {
                return ResourceManager.GetString("Image_Success_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins has been Uploaded Successfully.
        /// </summary>
        public static string Image_Success_Upload {
            get {
                return ResourceManager.GetString("Image_Success_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Images.
        /// </summary>
        public static string Images_1 {
            get {
                return ResourceManager.GetString("Images_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invitation has been sent to your email address.Please follow the instructions to complete the registration.
        /// </summary>
        public static string Invitation {
            get {
                return ResourceManager.GetString("Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Me.
        /// </summary>
        public static string Just_Me {
            get {
                return ResourceManager.GetString("Just_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Palo Alto, CA.
        /// </summary>
        public static string Loc_Ex {
            get {
                return ResourceManager.GetString("Loc_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your account.
        /// </summary>
        public static string Login_1 {
            get {
                return ResourceManager.GetString("Login_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login....
        /// </summary>
        public static string Login_Back {
            get {
                return ResourceManager.GetString("Login_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address/User Name and/or Password.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be tricky.
        /// </summary>
        public static string New_1 {
            get {
                return ResourceManager.GetString("New_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New, Again.
        /// </summary>
        public static string New_2 {
            get {
                return ResourceManager.GetString("New_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string New_3 {
            get {
                return ResourceManager.GetString("New_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password.
        /// </summary>
        public static string Old_1 {
            get {
                return ResourceManager.GetString("Old_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not created. Please click Change Password button and reset your Password.
        /// </summary>
        public static string Pass_Created {
            get {
                return ResourceManager.GetString("Pass_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your Password?.
        /// </summary>
        public static string Pass_Forgot {
            get {
                return ResourceManager.GetString("Pass_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password has been sent to your email address.
        /// </summary>
        public static string Pass_Reset {
            get {
                return ResourceManager.GetString("Pass_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been updated.
        /// </summary>
        public static string Pass_Updated {
            get {
                return ResourceManager.GetString("Pass_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Mismatch.
        /// </summary>
        public static string Password_Mismatch {
            get {
                return ResourceManager.GetString("Password_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new password in the last two textboxes.
        /// </summary>
        public static string Password_New {
            get {
                return ResourceManager.GetString("Password_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin images from any website as you browse the web with the.
        /// </summary>
        public static string Pin_1 {
            get {
                return ResourceManager.GetString("Pin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Pin It&quot; button.
        /// </summary>
        public static string Pin_2 {
            get {
                return ResourceManager.GetString("Pin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can pin.
        /// </summary>
        public static string Pin_6 {
            get {
                return ResourceManager.GetString("Pin_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Pin.
        /// </summary>
        public static string Pin_Add {
            get {
                return ResourceManager.GetString("Pin_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a http address (Url) and then click Find Images. Select the image by clicking the &quot;Prev&quot; and &quot;Next&quot; button below..
        /// </summary>
        public static string Pin_Add_Msg {
            get {
                return ResourceManager.GetString("Pin_Add_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create a board before adding pins..
        /// </summary>
        public static string Pin_Alert_Title {
            get {
                return ResourceManager.GetString("Pin_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this pin?.
        /// </summary>
        public static string Pin_Del_Msg {
            get {
                return ResourceManager.GetString("Pin_Del_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin It.
        /// </summary>
        public static string Pin_It {
            get {
                return ResourceManager.GetString("Pin_It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a Pin.
        /// </summary>
        public static string Pin_Upload {
            get {
                return ResourceManager.GetString("Pin_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the Browse button to select an Image file.
        /// </summary>
        public static string Pin_Upload_Msg {
            get {
                return ResourceManager.GetString("Pin_Upload_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinPolish.
        /// </summary>
        public static string Pinjimu {
            get {
                return ResourceManager.GetString("Pinjimu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        public static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNTS are your reward for sharing great content. The more you share and influence others, the more PTZ you earn. PTZ add up to amazing prices on the things you want from brands you love..
        /// </summary>
        public static string PNTS {
            get {
                return ResourceManager.GetString("PNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new idea boards (500 points max).
        /// </summary>
        public static string Point_Nib {
            get {
                return ResourceManager.GetString("Point_Nib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin ideas (100 points max per day).
        /// </summary>
        public static string Point_Pin {
            get {
                return ResourceManager.GetString("Point_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repin designs (100 points max per day).
        /// </summary>
        public static string Point_RePin {
            get {
                return ResourceManager.GetString("Point_RePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing up(one time).
        /// </summary>
        public static string Point_SignUp {
            get {
                return ResourceManager.GetString("Point_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post This To.
        /// </summary>
        public static string Post_This_To {
            get {
                return ResourceManager.GetString("Post_This_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repin.
        /// </summary>
        public static string Repin {
            get {
                return ResourceManager.GetString("Repin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an Invite.
        /// </summary>
        public static string Request_an_Invite {
            get {
                return ResourceManager.GetString("Request_an_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Invitation.
        /// </summary>
        public static string Request_Invitation {
            get {
                return ResourceManager.GetString("Request_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Board.
        /// </summary>
        public static string Save_Board {
            get {
                return ResourceManager.GetString("Save_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pin.
        /// </summary>
        public static string Save_Pin {
            get {
                return ResourceManager.GetString("Save_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        public static string Save_Profile {
            get {
                return ResourceManager.GetString("Save_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll To Top.
        /// </summary>
        public static string Scroll_To_Top {
            get {
                return ResourceManager.GetString("Scroll_To_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter search value, then select Pins or Boards or People and then click Search..
        /// </summary>
        public static string Search_Alert_1 {
            get {
                return ResourceManager.GetString("Search_Alert_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pins or Boards or People from the dropdown and then click Search..
        /// </summary>
        public static string Search_Alert_2 {
            get {
                return ResourceManager.GetString("Search_Alert_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Pins OR Boards OR People.
        /// </summary>
        public static string Search_Slogan {
            get {
                return ResourceManager.GetString("Search_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string Select_Category {
            get {
                return ResourceManager.GetString("Select_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shown publicly.
        /// </summary>
        public static string Set_1 {
            get {
                return ResourceManager.GetString("Set_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an invite to join.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up for PinPolish.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        public static string Spin {
            get {
                return ResourceManager.GetString("Spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFollow.
        /// </summary>
        public static string UnFollow {
            get {
                return ResourceManager.GetString("UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFollow Me.
        /// </summary>
        public static string UnFollow_Me {
            get {
                return ResourceManager.GetString("UnFollow_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Board.
        /// </summary>
        public static string Update_Board {
            get {
                return ResourceManager.GetString("Update_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string User_Not_Exist {
            get {
                return ResourceManager.GetString("User_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserName is invalid. Please use alphanumeric strings, -(hyphen), _(underscore) and numbers..
        /// </summary>
        public static string UserName_Alert {
            get {
                return ResourceManager.GetString("UserName_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAYS TO EARN.
        /// </summary>
        public static string Ways_to_Earn {
            get {
                return ResourceManager.GetString("Ways_to_Earn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAYS TO REDEEM.
        /// </summary>
        public static string Ways_to_Redeem {
            get {
                return ResourceManager.GetString("Ways_to_Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to win a free IPhone 4s!.
        /// </summary>
        public static string Win_IPhone {
            get {
                return ResourceManager.GetString("Win_IPhone", resourceCulture);
            }
        }
    }
}
