//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PindexProd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class cat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PindexProd.cat", typeof(cat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airbrush.
        /// </summary>
        public static string Airbrush {
            get {
                return ResourceManager.GetString("Airbrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary Rings.
        /// </summary>
        public static string Anniversary_Rings {
            get {
                return ResourceManager.GetString("Anniversary_Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural.
        /// </summary>
        public static string Architectural {
            get {
                return ResourceManager.GetString("Architectural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletic.
        /// </summary>
        public static string Athletic {
            get {
                return ResourceManager.GetString("Athletic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpacks.
        /// </summary>
        public static string Backpacks {
            get {
                return ResourceManager.GetString("Backpacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath &amp; Body.
        /// </summary>
        public static string Bath_Body {
            get {
                return ResourceManager.GetString("Bath_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Wedding.
        /// </summary>
        public static string Beach_Wedding {
            get {
                return ResourceManager.GetString("Beach_Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        public static string Beauty {
            get {
                return ResourceManager.GetString("Beauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Products.
        /// </summary>
        public static string Beauty_Products {
            get {
                return ResourceManager.GetString("Beauty_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Styles.
        /// </summary>
        public static string Beauty_Styles {
            get {
                return ResourceManager.GetString("Beauty_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belts.
        /// </summary>
        public static string Belts {
            get {
                return ResourceManager.GetString("Belts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Wedding.
        /// </summary>
        public static string Boat_Wedding {
            get {
                return ResourceManager.GetString("Boat_Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        public static string Boots {
            get {
                return ResourceManager.GetString("Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy&apos;s Clothes.
        /// </summary>
        public static string Boys_Clothes {
            get {
                return ResourceManager.GetString("Boys_Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy&apos;s Shoes.
        /// </summary>
        public static string Boys_Shoes {
            get {
                return ResourceManager.GetString("Boys_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracelets.
        /// </summary>
        public static string Bracelets {
            get {
                return ResourceManager.GetString("Bracelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridesmaid Dress.
        /// </summary>
        public static string Bridesmaid_Dress {
            get {
                return ResourceManager.GetString("Bridesmaid_Dress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrities.
        /// </summary>
        public static string Celebrities {
            get {
                return ResourceManager.GetString("Celebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clutches.
        /// </summary>
        public static string Clutches {
            get {
                return ResourceManager.GetString("Clutches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Schemes.
        /// </summary>
        public static string Color_Schemes {
            get {
                return ResourceManager.GetString("Color_Schemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was super easy.
        /// </summary>
        public static string Comment_Ans_1 {
            get {
                return ResourceManager.GetString("Comment_Ans_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was average.
        /// </summary>
        public static string Comment_Ans_2 {
            get {
                return ResourceManager.GetString("Comment_Ans_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was very hard.
        /// </summary>
        public static string Comment_Ans_3 {
            get {
                return ResourceManager.GetString("Comment_Ans_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only a professional could this..
        /// </summary>
        public static string Comment_Ans_4 {
            get {
                return ResourceManager.GetString("Comment_Ans_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how helpful was this.
        /// </summary>
        public static string Comment_Ques {
            get {
                return ResourceManager.GetString("Comment_Ques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy.
        /// </summary>
        public static string Crazy {
            get {
                return ResourceManager.GetString("Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration Ideas.
        /// </summary>
        public static string Decoration_Ideas {
            get {
                return ResourceManager.GetString("Decoration_Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors.
        /// </summary>
        public static string Doors {
            get {
                return ResourceManager.GetString("Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresses.
        /// </summary>
        public static string Dresses {
            get {
                return ResourceManager.GetString("Dresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings.
        /// </summary>
        public static string Earrings {
            get {
                return ResourceManager.GetString("Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement Rings.
        /// </summary>
        public static string Engagement_Rings {
            get {
                return ResourceManager.GetString("Engagement_Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensembles &amp; Sets.
        /// </summary>
        public static string Ensembles_Sets {
            get {
                return ResourceManager.GetString("Ensembles_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essentials.
        /// </summary>
        public static string Essentials {
            get {
                return ResourceManager.GetString("Essentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        public static string Exterior {
            get {
                return ResourceManager.GetString("Exterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        public static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion.
        /// </summary>
        public static string Fashion {
            get {
                return ResourceManager.GetString("Fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures.
        /// </summary>
        public static string Fixtures {
            get {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats.
        /// </summary>
        public static string Flats {
            get {
                return ResourceManager.GetString("Flats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooring.
        /// </summary>
        public static string Flooring {
            get {
                return ResourceManager.GetString("Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragrances.
        /// </summary>
        public static string Fragrances {
            get {
                return ResourceManager.GetString("Fragrances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeStyle.
        /// </summary>
        public static string FreeStyle {
            get {
                return ResourceManager.GetString("FreeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl&apos;s Clothes.
        /// </summary>
        public static string Girls_Clothes {
            get {
                return ResourceManager.GetString("Girls_Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl&apos;s Shoes.
        /// </summary>
        public static string Girls_Shoes {
            get {
                return ResourceManager.GetString("Girls_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitter.
        /// </summary>
        public static string Glitter {
            get {
                return ResourceManager.GetString("Glitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        public static string Gloves {
            get {
                return ResourceManager.GetString("Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string Gradient {
            get {
                return ResourceManager.GetString("Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Accessories.
        /// </summary>
        public static string Hair_Accessories {
            get {
                return ResourceManager.GetString("Hair_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Care.
        /// </summary>
        public static string Hair_Care {
            get {
                return ResourceManager.GetString("Hair_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair - How To.
        /// </summary>
        public static string Hair_How_To {
            get {
                return ResourceManager.GetString("Hair_How_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Styles.
        /// </summary>
        public static string Hair_Styles {
            get {
                return ResourceManager.GetString("Hair_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hats.
        /// </summary>
        public static string Hats {
            get {
                return ResourceManager.GetString("Hats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobos.
        /// </summary>
        public static string Hobos {
            get {
                return ResourceManager.GetString("Hobos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-To.
        /// </summary>
        public static string How_To {
            get {
                return ResourceManager.GetString("How_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Gallery.
        /// </summary>
        public static string How_To_Gallery {
            get {
                return ResourceManager.GetString("How_To_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        public static string Interior {
            get {
                return ResourceManager.GetString("Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interiors.
        /// </summary>
        public static string Interiors {
            get {
                return ResourceManager.GetString("Interiors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimates.
        /// </summary>
        public static string Intimates {
            get {
                return ResourceManager.GetString("Intimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackets.
        /// </summary>
        public static string Jackets {
            get {
                return ResourceManager.GetString("Jackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeans.
        /// </summary>
        public static string Jeans {
            get {
                return ResourceManager.GetString("Jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        public static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscapes.
        /// </summary>
        public static string Landscapes {
            get {
                return ResourceManager.GetString("Landscapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make-Up.
        /// </summary>
        public static string Make_Up {
            get {
                return ResourceManager.GetString("Make_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manicure.
        /// </summary>
        public static string Manicure {
            get {
                return ResourceManager.GetString("Manicure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity.
        /// </summary>
        public static string Maternity {
            get {
                return ResourceManager.GetString("Maternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matte.
        /// </summary>
        public static string Matte {
            get {
                return ResourceManager.GetString("Matte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mens.
        /// </summary>
        public static string Mens {
            get {
                return ResourceManager.GetString("Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic.
        /// </summary>
        public static string Metallic {
            get {
                return ResourceManager.GetString("Metallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Wedding.
        /// </summary>
        public static string Mountain_Wedding {
            get {
                return ResourceManager.GetString("Mountain_Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mules &amp; Clogs.
        /// </summary>
        public static string Mules_Clogs {
            get {
                return ResourceManager.GetString("Mules_Clogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi (3+).
        /// </summary>
        public static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail Polish.
        /// </summary>
        public static string Nail_Polish {
            get {
                return ResourceManager.GetString("Nail_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nails.
        /// </summary>
        public static string Nails {
            get {
                return ResourceManager.GetString("Nails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necklaces.
        /// </summary>
        public static string Necklaces {
            get {
                return ResourceManager.GetString("Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string Other_Settings {
            get {
                return ResourceManager.GetString("Other_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Touches.
        /// </summary>
        public static string Other_Touches {
            get {
                return ResourceManager.GetString("Other_Touches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outerwear.
        /// </summary>
        public static string Outerwear {
            get {
                return ResourceManager.GetString("Outerwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit.
        /// </summary>
        public static string Outfit {
            get {
                return ResourceManager.GetString("Outfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants.
        /// </summary>
        public static string Pants {
            get {
                return ResourceManager.GetString("Pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants &amp; Shorts.
        /// </summary>
        public static string Pants_Shorts {
            get {
                return ResourceManager.GetString("Pants_Shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Wedding.
        /// </summary>
        public static string Park_Wedding {
            get {
                return ResourceManager.GetString("Park_Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        public static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Tools.
        /// </summary>
        public static string Pattern_Tools {
            get {
                return ResourceManager.GetString("Pattern_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedicures.
        /// </summary>
        public static string Pedicures {
            get {
                return ResourceManager.GetString("Pedicures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Ideas.
        /// </summary>
        public static string Photo_Ideas {
            get {
                return ResourceManager.GetString("Photo_Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumps.
        /// </summary>
        public static string Pumps {
            get {
                return ResourceManager.GetString("Pumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Decor.
        /// </summary>
        public static string Reception_Decor {
            get {
                return ResourceManager.GetString("Reception_Decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Jewellery.
        /// </summary>
        public static string Regular_Jewellery {
            get {
                return ResourceManager.GetString("Regular_Jewellery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        public static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roof.
        /// </summary>
        public static string Roof {
            get {
                return ResourceManager.GetString("Roof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandals.
        /// </summary>
        public static string Sandals {
            get {
                return ResourceManager.GetString("Sandals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satchels.
        /// </summary>
        public static string Satchels {
            get {
                return ResourceManager.GetString("Satchels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarves.
        /// </summary>
        public static string Scarves {
            get {
                return ResourceManager.GetString("Scarves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny.
        /// </summary>
        public static string Shiny {
            get {
                return ResourceManager.GetString("Shiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirts.
        /// </summary>
        public static string Shirts {
            get {
                return ResourceManager.GetString("Shirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorts.
        /// </summary>
        public static string Shorts {
            get {
                return ResourceManager.GetString("Shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder.
        /// </summary>
        public static string Shoulder {
            get {
                return ResourceManager.GetString("Shoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an invite to join FreshPin.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Care.
        /// </summary>
        public static string Skin_Care {
            get {
                return ResourceManager.GetString("Skin_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skirts.
        /// </summary>
        public static string Skirts {
            get {
                return ResourceManager.GetString("Skirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Touches.
        /// </summary>
        public static string Special_Touches {
            get {
                return ResourceManager.GetString("Special_Touches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportswear.
        /// </summary>
        public static string Sportswear {
            get {
                return ResourceManager.GetString("Sportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stairs.
        /// </summary>
        public static string Stairs {
            get {
                return ResourceManager.GetString("Stairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        public static string Stamp {
            get {
                return ResourceManager.GetString("Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stilleto.
        /// </summary>
        public static string Stilleto {
            get {
                return ResourceManager.GetString("Stilleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string Suits {
            get {
                return ResourceManager.GetString("Suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglasses.
        /// </summary>
        public static string Sunglasses {
            get {
                return ResourceManager.GetString("Sunglasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweater.
        /// </summary>
        public static string Sweater {
            get {
                return ResourceManager.GetString("Sweater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweaters.
        /// </summary>
        public static string Sweaters {
            get {
                return ResourceManager.GetString("Sweaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimwear.
        /// </summary>
        public static string Swimwear {
            get {
                return ResourceManager.GetString("Swimwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatoos.
        /// </summary>
        public static string Tatoos {
            get {
                return ResourceManager.GetString("Tatoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        public static string ThreeD {
            get {
                return ResourceManager.GetString("ThreeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toes.
        /// </summary>
        public static string Toes {
            get {
                return ResourceManager.GetString("Toes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tops.
        /// </summary>
        public static string Tops {
            get {
                return ResourceManager.GetString("Tops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totes.
        /// </summary>
        public static string Totes {
            get {
                return ResourceManager.GetString("Totes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string Trim {
            get {
                return ResourceManager.GetString("Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuxedos.
        /// </summary>
        public static string Tuxedos {
            get {
                return ResourceManager.GetString("Tuxedos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Tone.
        /// </summary>
        public static string Two_Tone {
            get {
                return ResourceManager.GetString("Two_Tone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallets.
        /// </summary>
        public static string Wallets {
            get {
                return ResourceManager.GetString("Wallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watches.
        /// </summary>
        public static string Watches {
            get {
                return ResourceManager.GetString("Watches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        public static string Wedding {
            get {
                return ResourceManager.GetString("Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Cake.
        /// </summary>
        public static string Wedding_Cake {
            get {
                return ResourceManager.GetString("Wedding_Cake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Dress.
        /// </summary>
        public static string Wedding_Dress {
            get {
                return ResourceManager.GetString("Wedding_Dress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Flowers.
        /// </summary>
        public static string Wedding_Flowers {
            get {
                return ResourceManager.GetString("Wedding_Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Invitation.
        /// </summary>
        public static string Wedding_Invitation {
            get {
                return ResourceManager.GetString("Wedding_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Jewelry.
        /// </summary>
        public static string Wedding_Jewelry {
            get {
                return ResourceManager.GetString("Wedding_Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Sets.
        /// </summary>
        public static string Wedding_Sets {
            get {
                return ResourceManager.GetString("Wedding_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedges.
        /// </summary>
        public static string Wedges {
            get {
                return ResourceManager.GetString("Wedges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With People.
        /// </summary>
        public static string With_People {
            get {
                return ResourceManager.GetString("With_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womens.
        /// </summary>
        public static string Womens {
            get {
                return ResourceManager.GetString("Womens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s Bags.
        /// </summary>
        public static string Womens_Bags {
            get {
                return ResourceManager.GetString("Womens_Bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s Clothes.
        /// </summary>
        public static string Womens_Clothes {
            get {
                return ResourceManager.GetString("Womens_Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
