//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PindexProd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PindexProd.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Leader.
        /// </summary>
        public static string About_1 {
            get {
                return ResourceManager.GetString("About_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeing the latest content can help you chose inspiring things that others in your community may not have seen. New content is a great way to contribute to your community.
        /// </summary>
        public static string About_2 {
            get {
                return ResourceManager.GetString("About_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop-Pin.
        /// </summary>
        public static string About_3 {
            get {
                return ResourceManager.GetString("About_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our showrooms only show products that have been crowd sourced, so it helps you find high quality products quickly. These are usually the most fashionable items that the stores carry.
        /// </summary>
        public static string About_4 {
            get {
                return ResourceManager.GetString("About_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinpact.
        /// </summary>
        public static string About_5 {
            get {
                return ResourceManager.GetString("About_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mini-cause to support and promote. Your group of friends can all chip in and make a difference. Caring matters.
        /// </summary>
        public static string About_6 {
            get {
                return ResourceManager.GetString("About_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string About_7 {
            get {
                return ResourceManager.GetString("About_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umm.... Our mission is to make it easier to create inspiring pinboards! Ok, nobody is going to make a movie about how we went about shapin the world. We do not know where this hobby will lead, so let&apos;s have fun along the way.
        /// </summary>
        public static string About_8 {
            get {
                return ResourceManager.GetString("About_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450 Sources, Fresh Daily, Original Sources - Pin On!.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Board.
        /// </summary>
        public static string Board_1 {
            get {
                return ResourceManager.GetString("Board_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Name.
        /// </summary>
        public static string Board_2 {
            get {
                return ResourceManager.GetString("Board_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Board.
        /// </summary>
        public static string Board_3 {
            get {
                return ResourceManager.GetString("Board_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Board.
        /// </summary>
        public static string Board_4 {
            get {
                return ResourceManager.GetString("Board_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select Category.
        /// </summary>
        public static string Cat_1 {
            get {
                return ResourceManager.GetString("Cat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Category from.
        /// </summary>
        public static string Cat_2 {
            get {
                return ResourceManager.GetString("Cat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Category.
        /// </summary>
        public static string Cat_3 {
            get {
                return ResourceManager.GetString("Cat_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国的.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_Pass {
            get {
                return ResourceManager.GetString("Forgot_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshPin.
        /// </summary>
        public static string FreshPin {
            get {
                return ResourceManager.GetString("FreshPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is SiteName.
        /// </summary>
        public static string Help_1 {
            get {
                return ResourceManager.GetString("Help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a pin.
        /// </summary>
        public static string Help_10 {
            get {
                return ResourceManager.GetString("Help_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pin is an image that someone has added in any one of the source sites. You can browse through these images and quickly find new content for your own style or pinboard. To see the source of the pin, you can just mouse over the image.
        /// </summary>
        public static string Help_11 {
            get {
                return ResourceManager.GetString("Help_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you have the icons when you mouse over the image.
        /// </summary>
        public static string Help_12 {
            get {
                return ResourceManager.GetString("Help_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteName bring you the most recent images from over 450 sources that you can use to create your own boards on SiteName or on any of your favorite virtual boards. If you see an image you like, just click on the icon and you&apos;ll be able to pin the image to your board in Pinterest, Tumblr, Lockerz or Flickr.
        /// </summary>
        public static string Help_13 {
            get {
                return ResourceManager.GetString("Help_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the two links displayed when you mouse over the image.
        /// </summary>
        public static string Help_14 {
            get {
                return ResourceManager.GetString("Help_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you mouse over any image in SiteName, you will see two links. The first link is the source the image is from. Clicking on this link will take you to the image in the source site. The second link is the category the image has been placed under in SiteName. Clicking on this will take you to the SiteName board for that category.
        /// </summary>
        public static string Help_15 {
            get {
                return ResourceManager.GetString("Help_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Practices.
        /// </summary>
        public static string Help_2 {
            get {
                return ResourceManager.GetString("Help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Help_3 {
            get {
                return ResourceManager.GetString("Help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Can You Do Differently with SiteName.
        /// </summary>
        public static string Help_4 {
            get {
                return ResourceManager.GetString("Help_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        public static string Help_5 {
            get {
                return ResourceManager.GetString("Help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteName is a stream of images from over 450 curated sites. It is a simple and convenient way to find new content for your stylebook or pinboard.
        /// </summary>
        public static string Help_6 {
            get {
                return ResourceManager.GetString("Help_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We started SiteName because we wanted an easier way to get new ideas onto our pinboards.
        /// </summary>
        public static string Help_7 {
            get {
                return ResourceManager.GetString("Help_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simply wanted fresh content from original sources. So we built SiteName.
        /// </summary>
        public static string Help_8 {
            get {
                return ResourceManager.GetString("Help_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With SiteName you only browse unique images, filtered and sorted the way you want them. We try to eliminate all duplicates to save your time. Since most of our content comes from the original source it is easy to trace back. SiteName is a fun way to quickly discover new things.
        /// </summary>
        public static string Help_9 {
            get {
                return ResourceManager.GetString("Help_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    COPYRIGHT&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    SiteName (&quot;SiteName&quot;) respects the intellectual property rights of others and expects its users to do the same. It is SiteName policy, in appropriate circumstances and at its discretion, to disable and/or terminate the accounts of users who repeatedly infringe or are repeatedly charged with infringing the copyrights or other intellectual property rights of others.&lt;/p&gt;
        ///                &lt;p&gt;
        ///                    In accordance wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_CopyRight {
            get {
                return ResourceManager.GetString("Help_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    PIN PRACTICES&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    We curate SiteName to make sure all the pins are well categorized and of high quality.But the people who use SiteName make it so much more special with their contributions.
        ///                &lt;/p&gt;
        ///                &lt;p&gt;
        ///                    We&apos;ve taken the collective input of SiteName users and have laid down these guidelines that will help us keep the SiteName community positive, useful and clean.
        ///                &lt;/p&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Pin_Practices {
            get {
                return ResourceManager.GetString("Help_Pin_Practices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    PRIVACY POLICY&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    SiteName ( &quot; SiteName &quot;,&quot; we &quot;, &quot;us&quot;, &quot;our&quot; provides a Website located at &lt;a href=&quot;http://freshpin.com&quot;&gt; http://freshpin.com &lt;/a&gt;for users of the Website ( &quot; Member(s)&quot;,
        ///                    &lt;br /&gt;
        ///                    &quot; User(s) &quot;, &quot; you &quot; ). This Privacy Policy explains our policies regarding information you provide and we collect and how we may use or disclose that information. We value your privacy and provide this Pr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Privacy {
            get {
                return ResourceManager.GetString("Help_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///                    TERMS OF USE&lt;/h1&gt;
        ///                &lt;p&gt;
        ///                    Please read carefully the following terms and conditions. These Terms govern your access to and use of the Site and Services and all Site Content (defined below), and constitute a binding legal agreement between you and SiteName.&lt;/p&gt;
        ///                &lt;h3&gt;
        ///                    Key Terms related to Content&lt;/h3&gt;
        ///                &lt;p&gt;
        ///                    &quot; Content &quot; means text, graphics, images, music, software, audio, video,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help_Term {
            get {
                return ResourceManager.GetString("Help_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile picture.
        /// </summary>
        public static string Image_1 {
            get {
                return ResourceManager.GetString("Image_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Images.
        /// </summary>
        public static string Images_1 {
            get {
                return ResourceManager.GetString("Images_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Me.
        /// </summary>
        public static string Just_Me {
            get {
                return ResourceManager.GetString("Just_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Palo Alto, CA.
        /// </summary>
        public static string Loc_Ex {
            get {
                return ResourceManager.GetString("Loc_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your account.
        /// </summary>
        public static string Login_1 {
            get {
                return ResourceManager.GetString("Login_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be tricky.
        /// </summary>
        public static string New_1 {
            get {
                return ResourceManager.GetString("New_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New, Again.
        /// </summary>
        public static string New_2 {
            get {
                return ResourceManager.GetString("New_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string New_3 {
            get {
                return ResourceManager.GetString("New_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password.
        /// </summary>
        public static string Old_1 {
            get {
                return ResourceManager.GetString("Old_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin images from any website as you browse the web with the.
        /// </summary>
        public static string Pin_1 {
            get {
                return ResourceManager.GetString("Pin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Pin It&quot; button.
        /// </summary>
        public static string Pin_2 {
            get {
                return ResourceManager.GetString("Pin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Pin.
        /// </summary>
        public static string Pin_3 {
            get {
                return ResourceManager.GetString("Pin_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a Pin.
        /// </summary>
        public static string Pin_4 {
            get {
                return ResourceManager.GetString("Pin_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin It.
        /// </summary>
        public static string Pin_5 {
            get {
                return ResourceManager.GetString("Pin_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can pin.
        /// </summary>
        public static string Pin_6 {
            get {
                return ResourceManager.GetString("Pin_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pin.
        /// </summary>
        public static string Pin_7 {
            get {
                return ResourceManager.GetString("Pin_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Pin.
        /// </summary>
        public static string Pin_8 {
            get {
                return ResourceManager.GetString("Pin_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pin.
        /// </summary>
        public static string Pin_9 {
            get {
                return ResourceManager.GetString("Pin_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        public static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repin.
        /// </summary>
        public static string Repin {
            get {
                return ResourceManager.GetString("Repin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an Invite.
        /// </summary>
        public static string Request_an_Invite {
            get {
                return ResourceManager.GetString("Request_an_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Invitation.
        /// </summary>
        public static string Request_Invitation {
            get {
                return ResourceManager.GetString("Request_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        public static string Save_Profile {
            get {
                return ResourceManager.GetString("Save_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shown publicly.
        /// </summary>
        public static string Set_1 {
            get {
                return ResourceManager.GetString("Set_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an invite to join.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
