//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinjimu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class cat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinjimu.cat", typeof(cat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories and Decor.
        /// </summary>
        public static string Accessories_and_Decor {
            get {
                return ResourceManager.GetString("Accessories_and_Decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprons.
        /// </summary>
        public static string Aprons {
            get {
                return ResourceManager.GetString("Aprons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmChairs.
        /// </summary>
        public static string ArmChairs {
            get {
                return ResourceManager.GetString("ArmChairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork.
        /// </summary>
        public static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian.
        /// </summary>
        public static string Asian {
            get {
                return ResourceManager.GetString("Asian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Bedding.
        /// </summary>
        public static string Baby_Bedding {
            get {
                return ResourceManager.GetString("Baby_Bedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Swings And Bouncers.
        /// </summary>
        public static string Baby_Swings_And_Bouncers {
            get {
                return ResourceManager.GetString("Baby_Swings_And_Bouncers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Toys.
        /// </summary>
        public static string Baby_Toys {
            get {
                return ResourceManager.GetString("Baby_Toys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Carts.
        /// </summary>
        public static string Bar_Carts {
            get {
                return ResourceManager.GetString("Bar_Carts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Tables.
        /// </summary>
        public static string Bar_Tables {
            get {
                return ResourceManager.GetString("Bar_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars  Stools and Counter Stools.
        /// </summary>
        public static string Bars__Stools_and_Counter_Stools {
            get {
                return ResourceManager.GetString("Bars__Stools_and_Counter_Stools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barware.
        /// </summary>
        public static string Barware {
            get {
                return ResourceManager.GetString("Barware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basement.
        /// </summary>
        public static string Basement {
            get {
                return ResourceManager.GetString("Basement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskets.
        /// </summary>
        public static string Baskets {
            get {
                return ResourceManager.GetString("Baskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath and Spa Accessories.
        /// </summary>
        public static string Bath_and_Spa_Accessories {
            get {
                return ResourceManager.GetString("Bath_and_Spa_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath Mats.
        /// </summary>
        public static string Bath_Mats {
            get {
                return ResourceManager.GetString("Bath_Mats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath Products.
        /// </summary>
        public static string Bath_Products {
            get {
                return ResourceManager.GetString("Bath_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath Room Lighting and Vanity Lighting.
        /// </summary>
        public static string Bath_Room_Lighting_and_Vanity_Lighting {
            get {
                return ResourceManager.GetString("Bath_Room_Lighting_and_Vanity_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        public static string Bathroom {
            get {
                return ResourceManager.GetString("Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Countertops.
        /// </summary>
        public static string Bathroom_Countertops {
            get {
                return ResourceManager.GetString("Bathroom_Countertops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Faucets.
        /// </summary>
        public static string Bathroom_Faucets {
            get {
                return ResourceManager.GetString("Bathroom_Faucets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Mirrors.
        /// </summary>
        public static string Bathroom_Mirrors {
            get {
                return ResourceManager.GetString("Bathroom_Mirrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Sinks.
        /// </summary>
        public static string Bathroom_Sinks {
            get {
                return ResourceManager.GetString("Bathroom_Sinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Storage.
        /// </summary>
        public static string Bathroom_Storage {
            get {
                return ResourceManager.GetString("Bathroom_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Tile.
        /// </summary>
        public static string Bathroom_Tile {
            get {
                return ResourceManager.GetString("Bathroom_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom Vanities and Sink Consoles.
        /// </summary>
        public static string Bathroom_Vanities_and_Sink_Consoles {
            get {
                return ResourceManager.GetString("Bathroom_Vanities_and_Sink_Consoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathtubs.
        /// </summary>
        public static string Bathtubs {
            get {
                return ResourceManager.GetString("Bathtubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedding.
        /// </summary>
        public static string Bedding {
            get {
                return ResourceManager.GetString("Bedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom.
        /// </summary>
        public static string Bedroom {
            get {
                return ResourceManager.GetString("Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom Benches.
        /// </summary>
        public static string Bedroom_Benches {
            get {
                return ResourceManager.GetString("Bedroom_Benches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom Products.
        /// </summary>
        public static string Bedroom_Products {
            get {
                return ResourceManager.GetString("Bedroom_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beds.
        /// </summary>
        public static string Beds {
            get {
                return ResourceManager.GetString("Beds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benches.
        /// </summary>
        public static string Benches {
            get {
                return ResourceManager.GetString("Benches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookcases Cabinets and Computer Armoires.
        /// </summary>
        public static string Bookcases_Cabinets_and_Computer_Armoires {
            get {
                return ResourceManager.GetString("Bookcases_Cabinets_and_Computer_Armoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brackets.
        /// </summary>
        public static string Brackets {
            get {
                return ResourceManager.GetString("Brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffets and Sideboards.
        /// </summary>
        public static string Buffets_and_Sideboards {
            get {
                return ResourceManager.GetString("Buffets_and_Sideboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletin Board.
        /// </summary>
        public static string Bulletin_Board {
            get {
                return ResourceManager.GetString("Bulletin_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet And Drawer Organizers.
        /// </summary>
        public static string Cabinet_And_Drawer_Organizers {
            get {
                return ResourceManager.GetString("Cabinet_And_Drawer_Organizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Management.
        /// </summary>
        public static string Cable_Management {
            get {
                return ResourceManager.GetString("Cable_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle and Candle Holders.
        /// </summary>
        public static string Candle_and_Candle_Holders {
            get {
                return ResourceManager.GetString("Candle_and_Candle_Holders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet Flooring.
        /// </summary>
        public static string Carpet_Flooring {
            get {
                return ResourceManager.GetString("Carpet_Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celling Fans.
        /// </summary>
        public static string Celling_Fans {
            get {
                return ResourceManager.GetString("Celling_Fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celling Lighting.
        /// </summary>
        public static string Celling_Lighting {
            get {
                return ResourceManager.GetString("Celling_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular Shades.
        /// </summary>
        public static string Cellular_Shades {
            get {
                return ResourceManager.GetString("Cellular_Shades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairs.
        /// </summary>
        public static string Chairs {
            get {
                return ResourceManager.GetString("Chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chandeliers.
        /// </summary>
        public static string Chandeliers {
            get {
                return ResourceManager.GetString("Chandeliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Tables.
        /// </summary>
        public static string Changing_Tables {
            get {
                return ResourceManager.GetString("Changing_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Lighting.
        /// </summary>
        public static string Children_Lighting {
            get {
                return ResourceManager.GetString("Children_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cleaning supplies.
        /// </summary>
        public static string cleaning_supplies {
            get {
                return ResourceManager.GetString("cleaning_supplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clocks.
        /// </summary>
        public static string Clocks {
            get {
                return ResourceManager.GetString("Clocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closet.
        /// </summary>
        public static string Closet {
            get {
                return ResourceManager.GetString("Closet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closet Organizers.
        /// </summary>
        public static string Closet_Organizers {
            get {
                return ResourceManager.GetString("Closet_Organizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes and Shoes Organizers.
        /// </summary>
        public static string Clothes_and_Shoes_Organizers {
            get {
                return ResourceManager.GetString("Clothes_and_Shoes_Organizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes Racks.
        /// </summary>
        public static string Clothes_Racks {
            get {
                return ResourceManager.GetString("Clothes_Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothesline.
        /// </summary>
        public static string Clothesline {
            get {
                return ResourceManager.GetString("Clothesline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat Stands and Umbrella.
        /// </summary>
        public static string Coat_Stands_and_Umbrella {
            get {
                return ResourceManager.GetString("Coat_Stands_and_Umbrella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Tables.
        /// </summary>
        public static string Coffee_Tables {
            get {
                return ResourceManager.GetString("Coffee_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contemporary.
        /// </summary>
        public static string Contemporary {
            get {
                return ResourceManager.GetString("Contemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CookWare And BakeWare.
        /// </summary>
        public static string CookWare_And_BakeWare {
            get {
                return ResourceManager.GetString("CookWare_And_BakeWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crib Accessories.
        /// </summary>
        public static string Crib_Accessories {
            get {
                return ResourceManager.GetString("Crib_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cribs.
        /// </summary>
        public static string Cribs {
            get {
                return ResourceManager.GetString("Cribs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Poles.
        /// </summary>
        public static string Curtain_Poles {
            get {
                return ResourceManager.GetString("Curtain_Poles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtains.
        /// </summary>
        public static string Curtains {
            get {
                return ResourceManager.GetString("Curtains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Beds and Chaises.
        /// </summary>
        public static string Day_Beds_and_Chaises {
            get {
                return ResourceManager.GetString("Day_Beds_and_Chaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decals.
        /// </summary>
        public static string Decals {
            get {
                return ResourceManager.GetString("Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desk Accessories.
        /// </summary>
        public static string Desk_Accessories {
            get {
                return ResourceManager.GetString("Desk_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desks.
        /// </summary>
        public static string Desks {
            get {
                return ResourceManager.GetString("Desks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Chair Cushions.
        /// </summary>
        public static string Dining_Chair_Cushions {
            get {
                return ResourceManager.GetString("Dining_Chair_Cushions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Chairs and Benches.
        /// </summary>
        public static string Dining_Chairs_and_Benches {
            get {
                return ResourceManager.GetString("Dining_Chairs_and_Benches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Room.
        /// </summary>
        public static string Dining_Room {
            get {
                return ResourceManager.GetString("Dining_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Tables.
        /// </summary>
        public static string Dining_Tables {
            get {
                return ResourceManager.GetString("Dining_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinnerware.
        /// </summary>
        public static string Dinnerware {
            get {
                return ResourceManager.GetString("Dinnerware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Racks.
        /// </summary>
        public static string Dish_Racks {
            get {
                return ResourceManager.GetString("Dish_Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishtowels.
        /// </summary>
        public static string Dishtowels {
            get {
                return ResourceManager.GetString("Dishtowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dressers Chests and Bedroom Armoires.
        /// </summary>
        public static string Dressers_Chests_and_Bedroom_Armoires {
            get {
                return ResourceManager.GetString("Dressers_Chests_and_Bedroom_Armoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dryer racks.
        /// </summary>
        public static string dryer_racks {
            get {
                return ResourceManager.GetString("dryer_racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eclectic.
        /// </summary>
        public static string Eclectic {
            get {
                return ResourceManager.GetString("Eclectic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        public static string Exterior {
            get {
                return ResourceManager.GetString("Exterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabric.
        /// </summary>
        public static string Fabric {
            get {
                return ResourceManager.GetString("Fabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Room.
        /// </summary>
        public static string Family_Room {
            get {
                return ResourceManager.GetString("Family_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fencing.
        /// </summary>
        public static string Fencing {
            get {
                return ResourceManager.GetString("Fencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing Cabinets and Carts.
        /// </summary>
        public static string Filing_Cabinets_and_Carts {
            get {
                return ResourceManager.GetString("Filing_Cabinets_and_Carts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firepits.
        /// </summary>
        public static string Firepits {
            get {
                return ResourceManager.GetString("Firepits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplace Accessories.
        /// </summary>
        public static string Fireplace_Accessories {
            get {
                return ResourceManager.GetString("Fireplace_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplaces.
        /// </summary>
        public static string Fireplaces {
            get {
                return ResourceManager.GetString("Fireplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flateware.
        /// </summary>
        public static string Flateware {
            get {
                return ResourceManager.GetString("Flateware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Lamps.
        /// </summary>
        public static string Floor_Lamps {
            get {
                return ResourceManager.GetString("Floor_Lamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Tiles.
        /// </summary>
        public static string Floor_Tiles {
            get {
                return ResourceManager.GetString("Floor_Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Containers And Storage.
        /// </summary>
        public static string Food_Containers_And_Storage {
            get {
                return ResourceManager.GetString("Food_Containers_And_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        public static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Doors.
        /// </summary>
        public static string Front_Doors {
            get {
                return ResourceManager.GetString("Front_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        public static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage and Shed.
        /// </summary>
        public static string Garage_and_Shed {
            get {
                return ResourceManager.GetString("Garage_and_Shed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Doors.
        /// </summary>
        public static string Garage_Doors {
            get {
                return ResourceManager.GetString("Garage_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gazebos.
        /// </summary>
        public static string Gazebos {
            get {
                return ResourceManager.GetString("Gazebos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glassware.
        /// </summary>
        public static string Glassware {
            get {
                return ResourceManager.GetString("Glassware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granding Tools.
        /// </summary>
        public static string Granding_Tools {
            get {
                return ResourceManager.GetString("Granding_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouses.
        /// </summary>
        public static string Greenhouses {
            get {
                return ResourceManager.GetString("Greenhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grills.
        /// </summary>
        public static string Grills {
            get {
                return ResourceManager.GetString("Grills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Trees.
        /// </summary>
        public static string Hall_Trees {
            get {
                return ResourceManager.GetString("Hall_Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammocks.
        /// </summary>
        public static string Hammocks {
            get {
                return ResourceManager.GetString("Hammocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles.
        /// </summary>
        public static string Handles {
            get {
                return ResourceManager.GetString("Handles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headboards.
        /// </summary>
        public static string Headboards {
            get {
                return ResourceManager.GetString("Headboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highchairs.
        /// </summary>
        public static string Highchairs {
            get {
                return ResourceManager.GetString("Highchairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Decorations.
        /// </summary>
        public static string Holiday_Decorations {
            get {
                return ResourceManager.GetString("Holiday_Decorations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Electronics.
        /// </summary>
        public static string Home_Electronics {
            get {
                return ResourceManager.GetString("Home_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Fragrance.
        /// </summary>
        public static string Home_Fragrance {
            get {
                return ResourceManager.GetString("Home_Fragrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Gym.
        /// </summary>
        public static string Home_Gym {
            get {
                return ResourceManager.GetString("Home_Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Office.
        /// </summary>
        public static string Home_Office {
            get {
                return ResourceManager.GetString("Home_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Office Products.
        /// </summary>
        public static string Home_Office_Products {
            get {
                return ResourceManager.GetString("Home_Office_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooks and Hangers.
        /// </summary>
        public static string Hooks_and_Hangers {
            get {
                return ResourceManager.GetString("Hooks_and_Hangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housekeeping.
        /// </summary>
        public static string Housekeeping {
            get {
                return ResourceManager.GetString("Housekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor Fountains.
        /// </summary>
        public static string Indoor_Fountains {
            get {
                return ResourceManager.GetString("Indoor_Fountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor Pots and Planters.
        /// </summary>
        public static string Indoor_Pots_and_Planters {
            get {
                return ResourceManager.GetString("Indoor_Pots_and_Planters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior Doors.
        /// </summary>
        public static string Interior_Doors {
            get {
                return ResourceManager.GetString("Interior_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ironing boards.
        /// </summary>
        public static string Ironing_boards {
            get {
                return ResourceManager.GetString("Ironing_boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irons.
        /// </summary>
        public static string Irons {
            get {
                return ResourceManager.GetString("Irons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation Equipment.
        /// </summary>
        public static string Irrigation_Equipment {
            get {
                return ResourceManager.GetString("Irrigation_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Bedding.
        /// </summary>
        public static string Kids_Bedding {
            get {
                return ResourceManager.GetString("Kids_Bedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Beds.
        /// </summary>
        public static string Kids_Beds {
            get {
                return ResourceManager.GetString("Kids_Beds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Chairs.
        /// </summary>
        public static string Kids_Chairs {
            get {
                return ResourceManager.GetString("Kids_Chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Decor.
        /// </summary>
        public static string Kids_Decor {
            get {
                return ResourceManager.GetString("Kids_Decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Dressers.
        /// </summary>
        public static string Kids_Dressers {
            get {
                return ResourceManager.GetString("Kids_Dressers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Products.
        /// </summary>
        public static string Kids_Products {
            get {
                return ResourceManager.GetString("Kids_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Rugs.
        /// </summary>
        public static string Kids_Rugs {
            get {
                return ResourceManager.GetString("Kids_Rugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Tables.
        /// </summary>
        public static string Kids_Tables {
            get {
                return ResourceManager.GetString("Kids_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Toys.
        /// </summary>
        public static string Kids_Toys {
            get {
                return ResourceManager.GetString("Kids_Toys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitchen Cabinets.
        /// </summary>
        public static string kitchen_Cabinets {
            get {
                return ResourceManager.GetString("kitchen_Cabinets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Countertops.
        /// </summary>
        public static string Kitchen_Countertops {
            get {
                return ResourceManager.GetString("Kitchen_Countertops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Faucets.
        /// </summary>
        public static string Kitchen_Faucets {
            get {
                return ResourceManager.GetString("Kitchen_Faucets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Islands and Kitchen Crafts.
        /// </summary>
        public static string Kitchen_Islands_and_Kitchen_Crafts {
            get {
                return ResourceManager.GetString("Kitchen_Islands_and_Kitchen_Crafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Lighting And Cabinet Lighting.
        /// </summary>
        public static string Kitchen_Lighting_And_Cabinet_Lighting {
            get {
                return ResourceManager.GetString("Kitchen_Lighting_And_Cabinet_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Products.
        /// </summary>
        public static string Kitchen_Products {
            get {
                return ResourceManager.GetString("Kitchen_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Sinks.
        /// </summary>
        public static string Kitchen_Sinks {
            get {
                return ResourceManager.GetString("Kitchen_Sinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Tile.
        /// </summary>
        public static string Kitchen_Tile {
            get {
                return ResourceManager.GetString("Kitchen_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Tools.
        /// </summary>
        public static string Kitchen_Tools {
            get {
                return ResourceManager.GetString("Kitchen_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Trash Cans.
        /// </summary>
        public static string Kitchen_Trash_Cans {
            get {
                return ResourceManager.GetString("Kitchen_Trash_Cans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knives and Chopping Boards.
        /// </summary>
        public static string Knives_and_Chopping_Boards {
            get {
                return ResourceManager.GetString("Knives_and_Chopping_Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knobs.
        /// </summary>
        public static string Knobs {
            get {
                return ResourceManager.GetString("Knobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ladders and step stools.
        /// </summary>
        public static string ladders_and_step_stools {
            get {
                return ResourceManager.GetString("ladders_and_step_stools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminate Florring.
        /// </summary>
        public static string Laminate_Florring {
            get {
                return ResourceManager.GetString("Laminate_Florring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Shades.
        /// </summary>
        public static string Lamp_Shades {
            get {
                return ResourceManager.GetString("Lamp_Shades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry products.
        /// </summary>
        public static string Laundry_products {
            get {
                return ResourceManager.GetString("Laundry_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry Room.
        /// </summary>
        public static string Laundry_Room {
            get {
                return ResourceManager.GetString("Laundry_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry Room appliances.
        /// </summary>
        public static string Laundry_Room_appliances {
            get {
                return ResourceManager.GetString("Laundry_Room_appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Bulbs.
        /// </summary>
        public static string Light_Bulbs {
            get {
                return ResourceManager.GetString("Light_Bulbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightining.
        /// </summary>
        public static string Lightining {
            get {
                return ResourceManager.GetString("Lightining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Room.
        /// </summary>
        public static string Living_Room {
            get {
                return ResourceManager.GetString("Living_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love Seats.
        /// </summary>
        public static string Love_Seats {
            get {
                return ResourceManager.GetString("Love_Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine Racks.
        /// </summary>
        public static string Magazine_Racks {
            get {
                return ResourceManager.GetString("Magazine_Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Kitchen Appliances.
        /// </summary>
        public static string Major_Kitchen_Appliances {
            get {
                return ResourceManager.GetString("Major_Kitchen_Appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makeup Mirrors.
        /// </summary>
        public static string Makeup_Mirrors {
            get {
                return ResourceManager.GetString("Makeup_Mirrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Room.
        /// </summary>
        public static string Media_Room {
            get {
                return ResourceManager.GetString("Media_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Storage.
        /// </summary>
        public static string Media_Storage {
            get {
                return ResourceManager.GetString("Media_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Cabinets.
        /// </summary>
        public static string Medicine_Cabinets {
            get {
                return ResourceManager.GetString("Medicine_Cabinets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean.
        /// </summary>
        public static string Mediterranean {
            get {
                return ResourceManager.GetString("Mediterranean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirrors.
        /// </summary>
        public static string Mirrors {
            get {
                return ResourceManager.GetString("Mirrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiles.
        /// </summary>
        public static string Mobiles {
            get {
                return ResourceManager.GetString("Mobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string Modern {
            get {
                return ResourceManager.GetString("Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mops brooms and Dustpans.
        /// </summary>
        public static string Mops_brooms_and_Dustpans {
            get {
                return ResourceManager.GetString("Mops_brooms_and_Dustpans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napkin Rings.
        /// </summary>
        public static string Napkin_Rings {
            get {
                return ResourceManager.GetString("Napkin_Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightstands and Beside Tables.
        /// </summary>
        public static string Nightstands_and_Beside_Tables {
            get {
                return ResourceManager.GetString("Nightstands_and_Beside_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nursery Decor.
        /// </summary>
        public static string Nursery_Decor {
            get {
                return ResourceManager.GetString("Nursery_Decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottomans and Cubes.
        /// </summary>
        public static string Ottomans_and_Cubes {
            get {
                return ResourceManager.GetString("Ottomans_and_Cubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Decor.
        /// </summary>
        public static string Outdoor_Decor {
            get {
                return ResourceManager.GetString("Outdoor_Decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Fabric.
        /// </summary>
        public static string Outdoor_Fabric {
            get {
                return ResourceManager.GetString("Outdoor_Fabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Lighting.
        /// </summary>
        public static string Outdoor_Lighting {
            get {
                return ResourceManager.GetString("Outdoor_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Pillows.
        /// </summary>
        public static string Outdoor_Pillows {
            get {
                return ResourceManager.GetString("Outdoor_Pillows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Playsets.
        /// </summary>
        public static string Outdoor_Playsets {
            get {
                return ResourceManager.GetString("Outdoor_Playsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Products.
        /// </summary>
        public static string Outdoor_Products {
            get {
                return ResourceManager.GetString("Outdoor_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Rugs.
        /// </summary>
        public static string Outdoor_Rugs {
            get {
                return ResourceManager.GetString("Outdoor_Rugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Swingsets.
        /// </summary>
        public static string Outdoor_Swingsets {
            get {
                return ResourceManager.GetString("Outdoor_Swingsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Umbrellas.
        /// </summary>
        public static string Outdoor_Umbrellas {
            get {
                return ResourceManager.GetString("Outdoor_Umbrellas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oven Mits And Pot Holders.
        /// </summary>
        public static string Oven_Mits_And_Pot_Holders {
            get {
                return ResourceManager.GetString("Oven_Mits_And_Pot_Holders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paints Stains and Glazes.
        /// </summary>
        public static string Paints_Stains_and_Glazes {
            get {
                return ResourceManager.GetString("Paints_Stains_and_Glazes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panty.
        /// </summary>
        public static string Panty {
            get {
                return ResourceManager.GetString("Panty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patio.
        /// </summary>
        public static string Patio {
            get {
                return ResourceManager.GetString("Patio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patio Furniture and Outdoor Furniture.
        /// </summary>
        public static string Patio_Furniture_and_Outdoor_Furniture {
            get {
                return ResourceManager.GetString("Patio_Furniture_and_Outdoor_Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pendent Lighting.
        /// </summary>
        public static string pendent_Lighting {
            get {
                return ResourceManager.GetString("pendent_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Accessories.
        /// </summary>
        public static string Pet_Accessories {
            get {
                return ResourceManager.GetString("Pet_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillows.
        /// </summary>
        public static string Pillows {
            get {
                return ResourceManager.GetString("Pillows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plants.
        /// </summary>
        public static string Plants {
            get {
                return ResourceManager.GetString("Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string Pool {
            get {
                return ResourceManager.GetString("Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porch.
        /// </summary>
        public static string Porch {
            get {
                return ResourceManager.GetString("Porch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot Racks.
        /// </summary>
        public static string Pot_Racks {
            get {
                return ResourceManager.GetString("Pot_Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powder Room.
        /// </summary>
        public static string Powder_Room {
            get {
                return ResourceManager.GetString("Powder_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefab Studios.
        /// </summary>
        public static string Prefab_Studios {
            get {
                return ResourceManager.GetString("Prefab_Studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulls.
        /// </summary>
        public static string Pulls {
            get {
                return ResourceManager.GetString("Pulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recessed Lighting.
        /// </summary>
        public static string Recessed_Lighting {
            get {
                return ResourceManager.GetString("Recessed_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retainer Walls.
        /// </summary>
        public static string Retainer_Walls {
            get {
                return ResourceManager.GetString("Retainer_Walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocking Chairs.
        /// </summary>
        public static string Rocking_Chairs {
            get {
                return ResourceManager.GetString("Rocking_Chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocking Chairs And Gliders.
        /// </summary>
        public static string Rocking_Chairs_And_Gliders {
            get {
                return ResourceManager.GetString("Rocking_Chairs_And_Gliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller Blinds.
        /// </summary>
        public static string Roller_Blinds {
            get {
                return ResourceManager.GetString("Roller_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roman Blinds.
        /// </summary>
        public static string Roman_Blinds {
            get {
                return ResourceManager.GetString("Roman_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugs.
        /// </summary>
        public static string Rugs {
            get {
                return ResourceManager.GetString("Rugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Doors.
        /// </summary>
        public static string Screen_Doors {
            get {
                return ResourceManager.GetString("Screen_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens and Wall Dividers.
        /// </summary>
        public static string Screens_and_Wall_Dividers {
            get {
                return ResourceManager.GetString("Screens_and_Wall_Dividers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectional Sofas.
        /// </summary>
        public static string Sectional_Sofas {
            get {
                return ResourceManager.GetString("Sectional_Sofas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveware.
        /// </summary>
        public static string Serveware {
            get {
                return ResourceManager.GetString("Serveware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheds.
        /// </summary>
        public static string Sheds {
            get {
                return ResourceManager.GetString("Sheds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoeracks.
        /// </summary>
        public static string Shoeracks {
            get {
                return ResourceManager.GetString("Shoeracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower Caddies.
        /// </summary>
        public static string Shower_Caddies {
            get {
                return ResourceManager.GetString("Shower_Caddies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower Curtains.
        /// </summary>
        public static string Shower_Curtains {
            get {
                return ResourceManager.GetString("Shower_Curtains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showers.
        /// </summary>
        public static string Showers {
            get {
                return ResourceManager.GetString("Showers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Tables and Accent Tables.
        /// </summary>
        public static string Side_Tables_and_Accent_Tables {
            get {
                return ResourceManager.GetString("Side_Tables_and_Accent_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skylights.
        /// </summary>
        public static string Skylights {
            get {
                return ResourceManager.GetString("Skylights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Kitchen Appliances.
        /// </summary>
        public static string Small_Kitchen_Appliances {
            get {
                return ResourceManager.GetString("Small_Kitchen_Appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofa Beds.
        /// </summary>
        public static string Sofa_Beds {
            get {
                return ResourceManager.GetString("Sofa_Beds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofas.
        /// </summary>
        public static string Sofas {
            get {
                return ResourceManager.GetString("Sofas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        public static string Spaces {
            get {
                return ResourceManager.GetString("Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staircase.
        /// </summary>
        public static string Staircase {
            get {
                return ResourceManager.GetString("Staircase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stencils.
        /// </summary>
        public static string Stencils {
            get {
                return ResourceManager.GetString("Stencils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage and Organization.
        /// </summary>
        public static string Storage_and_Organization {
            get {
                return ResourceManager.GetString("Storage_and_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Boxes.
        /// </summary>
        public static string Storage_Boxes {
            get {
                return ResourceManager.GetString("Storage_Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switchplates.
        /// </summary>
        public static string Switchplates {
            get {
                return ResourceManager.GetString("Switchplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Lamps.
        /// </summary>
        public static string Table_Lamps {
            get {
                return ResourceManager.GetString("Table_Lamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Linens.
        /// </summary>
        public static string Table_Linens {
            get {
                return ResourceManager.GetString("Table_Linens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabletop.
        /// </summary>
        public static string Tabletop {
            get {
                return ResourceManager.GetString("Tabletop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Chairs.
        /// </summary>
        public static string Task_Chairs {
            get {
                return ResourceManager.GetString("Task_Chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws.
        /// </summary>
        public static string Throws {
            get {
                return ResourceManager.GetString("Throws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilet Accessories.
        /// </summary>
        public static string Toilet_Accessories {
            get {
                return ResourceManager.GetString("Toilet_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilets.
        /// </summary>
        public static string Toilets {
            get {
                return ResourceManager.GetString("Toilets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towel Bars and Hooks.
        /// </summary>
        public static string Towel_Bars_and_Hooks {
            get {
                return ResourceManager.GetString("Towel_Bars_and_Hooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towels.
        /// </summary>
        public static string Towels {
            get {
                return ResourceManager.GetString("Towels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toy Storage.
        /// </summary>
        public static string Toy_Storage {
            get {
                return ResourceManager.GetString("Toy_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Lighting.
        /// </summary>
        public static string Track_Lighting {
            get {
                return ResourceManager.GetString("Track_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        public static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string Trends {
            get {
                return ResourceManager.GetString("Trends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical.
        /// </summary>
        public static string Tropical {
            get {
                return ResourceManager.GetString("Tropical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upholstery Fabric.
        /// </summary>
        public static string Upholstery_Fabric {
            get {
                return ResourceManager.GetString("Upholstery_Fabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Tubs.
        /// </summary>
        public static string Utility_Tubs {
            get {
                return ResourceManager.GetString("Utility_Tubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum cleaners.
        /// </summary>
        public static string Vacuum_cleaners {
            get {
                return ResourceManager.GetString("Vacuum_cleaners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vases.
        /// </summary>
        public static string Vases {
            get {
                return ResourceManager.GetString("Vases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venetian Blinds.
        /// </summary>
        public static string Venetian_Blinds {
            get {
                return ResourceManager.GetString("Venetian_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Blinds.
        /// </summary>
        public static string Vertical_Blinds {
            get {
                return ResourceManager.GetString("Vertical_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinyl Flooring.
        /// </summary>
        public static string Vinyl_Flooring {
            get {
                return ResourceManager.GetString("Vinyl_Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Sconces.
        /// </summary>
        public static string Wall_Sconces {
            get {
                return ResourceManager.GetString("Wall_Sconces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Shelves.
        /// </summary>
        public static string Wall_Shelves {
            get {
                return ResourceManager.GetString("Wall_Shelves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string Wallpaper {
            get {
                return ResourceManager.GetString("Wallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Baskets.
        /// </summary>
        public static string Waste_Baskets {
            get {
                return ResourceManager.GetString("Waste_Baskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Blinds.
        /// </summary>
        public static string Window_Blinds {
            get {
                return ResourceManager.GetString("Window_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Treatment.
        /// </summary>
        public static string Window_Treatment {
            get {
                return ResourceManager.GetString("Window_Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows and Doors.
        /// </summary>
        public static string Windows_and_Doors {
            get {
                return ResourceManager.GetString("Windows_and_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine Cellar.
        /// </summary>
        public static string Wine_Cellar {
            get {
                return ResourceManager.GetString("Wine_Cellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine Racks.
        /// </summary>
        public static string Wine_Racks {
            get {
                return ResourceManager.GetString("Wine_Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Flooring.
        /// </summary>
        public static string Wood_Flooring {
            get {
                return ResourceManager.GetString("Wood_Flooring", resourceCulture);
            }
        }
    }
}
