//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\App_Data\\ATDatabase.mdf" +
            ";Integrated Security=True;User Instance=True")]
        public string ATDatabaseConnectionString {
            get {
                return ((string)(this["ATDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\App_Data\\CustomerDataba" +
            "se.mdf;Integrated Security=True;User Instance=True")]
        public string CustomerDatabaseConnectionString {
            get {
                return ((string)(this["CustomerDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<vc:Chart xmlns:vc=""clr-namespace:Visifire.Charts;assembly=SLVisifire.Charts"" Width=""{0}"" Height=""{1}"" BorderThickness=""0"" Theme=""Theme3"" View3D=""True"" AnimationEnabled=""True"" Watermark=""True"" LightingEnabled=""True""  Bevel=""True""  ShadowEnabled=""True"" >
    <vc:Chart.Titles>
        <vc:Title Text=""{2}"" />
    </vc:Chart.Titles>
    <vc:Chart.Legends>
        <vc:Legend Enabled=""True"" HorizontalAlignment=""Center"" />
    </vc:Chart.Legends>
    <vc:Chart.AxesX>
        <vc:Axis Title=""{3}"" />
    </vc:Chart.AxesX>
    <vc:Chart.AxesY>
        <vc:Axis Title=""{4}"" AxisType=""Primary"" AxisMinimum=""{5}"" AxisMaximum=""{6}"" />
    </vc:Chart.AxesY>
    <vc:Chart.Series>
        <vc:DataSeries RenderAs=""Column"" AxisYType=""Primary""  >
            <vc:DataSeries.DataPoints>{7}</vc:DataSeries.DataPoints>
        </vc:DataSeries>
    </vc:Chart.Series>
</vc:Chart>")]
        public string ColumnGraphXaml {
            get {
                return ((string)(this["ColumnGraphXaml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<vc:Chart xmlns:vc=""clr-namespace:Visifire.Charts;assembly=SLVisifire.Charts""  Bevel=""True""
Width=""{0}"" Height=""{1}"" Theme=""Theme3"" AnimatedUpdate=""true"">

<vc:Chart.Titles>
<vc:Title Text=""{2}""/>
</vc:Chart.Titles>

<vc:Chart.AxesX>
<vc:Axis Title=""{3}""  >
<vc:Axis.AxisLabels>
<vc:AxisLabels Angle=""-30""/>
</vc:Axis.AxisLabels>
</vc:Axis>
</vc:Chart.AxesX>

<vc:Chart.AxesY>
<vc:Axis AxisMinimum=""{4}"" AxisMaximum=""{5}"" Title=""{6}"" />
</vc:Chart.AxesY>

<vc:Chart.Legends>
<vc:Legend x:Name=""Legend1"" Background=""Black"" LightingEnabled=""False"" FontSize=""10""/>
</vc:Chart.Legends>

<vc:Chart.Series>
{7}
</vc:Chart.Series>
</vc:Chart>")]
        public string LineGraphXaml {
            get {
                return ((string)(this["LineGraphXaml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<vc:Chart xmlns:vc=""clr-namespace:Visifire.Charts;assembly=SLVisifire.Charts"" Width=""{0}"" Height=""{1}"" BorderThickness=""0"" Theme=""Theme3"" View3D=""True"" AnimationEnabled=""True"" Watermark=""True"" LightingEnabled=""True""  Bevel=""True""  ShadowEnabled=""True"" >
    <vc:Chart.Titles>
        <vc:Title Text=""{2}"" />
    </vc:Chart.Titles>
{3}
    <vc:Chart.Legends>
        <vc:Legend Enabled=""True"" HorizontalAlignment=""Center"" />
    </vc:Chart.Legends>
    <vc:Chart.AxesX>
        <vc:Axis Title=""{4}"" />
    </vc:Chart.AxesX>
    <vc:Chart.AxesY>
        <vc:Axis Title=""{5}"" AxisType=""Primary"" AxisMinimum=""{6}"" AxisMaximum=""{7}"" />
    </vc:Chart.AxesY>
    <vc:Chart.Series>
        <vc:DataSeries RenderAs=""Column"" AxisYType=""Primary""  >
            <vc:DataSeries.DataPoints>{8}</vc:DataSeries.DataPoints>
        </vc:DataSeries>
    </vc:Chart.Series>
</vc:Chart>")]
        public string ColumnGraphXamlWithTrendLines {
            get {
                return ((string)(this["ColumnGraphXamlWithTrendLines"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<vc:Chart xmlns:vc=""clr-namespace:Visifire.Charts;assembly=SLVisifire.Charts""  Bevel=""True""
Width=""{0}"" Height=""{1}"" Theme=""Theme3"" AnimatedUpdate=""true"">

<vc:Chart.Titles>
<vc:Title Text=""{2}""/>
</vc:Chart.Titles>
{3}
<vc:Chart.AxesX>
<vc:Axis Title=""{4}""  >
<vc:Axis.AxisLabels>
<vc:AxisLabels Angle=""-30""/>
</vc:Axis.AxisLabels>
</vc:Axis>
</vc:Chart.AxesX>

<vc:Chart.AxesY>
<vc:Axis AxisMinimum=""{5}"" AxisMaximum=""{6}"" Title=""{7}"" />
</vc:Chart.AxesY>

<vc:Chart.Legends>
<vc:Legend x:Name=""Legend1"" Background=""Black"" LightingEnabled=""False"" FontSize=""10""/>
</vc:Chart.Legends>

<vc:Chart.Series>
{8}
</vc:Chart.Series>
</vc:Chart>")]
        public string LineGraphXamlWithTrendLines {
            get {
                return ((string)(this["LineGraphXamlWithTrendLines"]));
            }
        }
    }
}
