//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Nails.Nails.edmx
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PinStatsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PinStatsEntities object using the connection string found in the 'PinStatsEntities' section of the application configuration file.
        /// </summary>
        public PinStatsEntities() : base("name=PinStatsEntities", "PinStatsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PinStatsEntities object.
        /// </summary>
        public PinStatsEntities(string connectionString) : base(connectionString, "PinStatsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PinStatsEntities object.
        /// </summary>
        public PinStatsEntities(EntityConnection connection) : base(connection, "PinStatsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<people> people
        {
            get
            {
                if ((_people == null))
                {
                    _people = base.CreateObjectSet<people>("people");
                }
                return _people;
            }
        }
        private ObjectSet<people> _people;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_people> vw_people
        {
            get
            {
                if ((_vw_people == null))
                {
                    _vw_people = base.CreateObjectSet<vw_people>("vw_people");
                }
                return _vw_people;
            }
        }
        private ObjectSet<vw_people> _vw_people;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the people EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopeople(people people)
        {
            base.AddObject("people", people);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_people EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_people(vw_people vw_people)
        {
            base.AddObject("vw_people", vw_people);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PinStatsModel", Name="people")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class people : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new people object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static people Createpeople(global::System.Int32 id)
        {
            people people = new people();
            people.Id = id;
            return people;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PinURL
        {
            get
            {
                return _PinURL;
            }
            set
            {
                OnPinURLChanging(value);
                ReportPropertyChanging("PinURL");
                _PinURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PinURL");
                OnPinURLChanged();
            }
        }
        private global::System.String _PinURL;
        partial void OnPinURLChanging(global::System.String value);
        partial void OnPinURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Followers
        {
            get
            {
                return _Followers;
            }
            set
            {
                OnFollowersChanging(value);
                ReportPropertyChanging("Followers");
                _Followers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Followers");
                OnFollowersChanged();
            }
        }
        private Nullable<global::System.Int32> _Followers;
        partial void OnFollowersChanging(Nullable<global::System.Int32> value);
        partial void OnFollowersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Likes
        {
            get
            {
                return _Likes;
            }
            set
            {
                OnLikesChanging(value);
                ReportPropertyChanging("Likes");
                _Likes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Likes");
                OnLikesChanged();
            }
        }
        private Nullable<global::System.Int32> _Likes;
        partial void OnLikesChanging(Nullable<global::System.Int32> value);
        partial void OnLikesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pins
        {
            get
            {
                return _Pins;
            }
            set
            {
                OnPinsChanging(value);
                ReportPropertyChanging("Pins");
                _Pins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pins");
                OnPinsChanged();
            }
        }
        private Nullable<global::System.Int32> _Pins;
        partial void OnPinsChanging(Nullable<global::System.Int32> value);
        partial void OnPinsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Following
        {
            get
            {
                return _Following;
            }
            set
            {
                OnFollowingChanging(value);
                ReportPropertyChanging("Following");
                _Following = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Following");
                OnFollowingChanged();
            }
        }
        private Nullable<global::System.Int32> _Following;
        partial void OnFollowingChanging(Nullable<global::System.Int32> value);
        partial void OnFollowingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Board
        {
            get
            {
                return _Board;
            }
            set
            {
                OnBoardChanging(value);
                ReportPropertyChanging("Board");
                _Board = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Board");
                OnBoardChanged();
            }
        }
        private global::System.String _Board;
        partial void OnBoardChanging(global::System.String value);
        partial void OnBoardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoardURL
        {
            get
            {
                return _BoardURL;
            }
            set
            {
                OnBoardURLChanging(value);
                ReportPropertyChanging("BoardURL");
                _BoardURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BoardURL");
                OnBoardURLChanged();
            }
        }
        private global::System.String _BoardURL;
        partial void OnBoardURLChanging(global::System.String value);
        partial void OnBoardURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoardTitle
        {
            get
            {
                return _BoardTitle;
            }
            set
            {
                OnBoardTitleChanging(value);
                ReportPropertyChanging("BoardTitle");
                _BoardTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BoardTitle");
                OnBoardTitleChanged();
            }
        }
        private global::System.String _BoardTitle;
        partial void OnBoardTitleChanging(global::System.String value);
        partial void OnBoardTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoardFollowers
        {
            get
            {
                return _BoardFollowers;
            }
            set
            {
                OnBoardFollowersChanging(value);
                ReportPropertyChanging("BoardFollowers");
                _BoardFollowers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BoardFollowers");
                OnBoardFollowersChanged();
            }
        }
        private Nullable<global::System.Int32> _BoardFollowers;
        partial void OnBoardFollowersChanging(Nullable<global::System.Int32> value);
        partial void OnBoardFollowersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoardPins
        {
            get
            {
                return _BoardPins;
            }
            set
            {
                OnBoardPinsChanging(value);
                ReportPropertyChanging("BoardPins");
                _BoardPins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BoardPins");
                OnBoardPinsChanged();
            }
        }
        private Nullable<global::System.Int32> _BoardPins;
        partial void OnBoardPinsChanging(Nullable<global::System.Int32> value);
        partial void OnBoardPinsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PinStatsModel", Name="vw_people")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_people : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_people object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static vw_people Createvw_people(global::System.Int32 id)
        {
            vw_people vw_people = new vw_people();
            vw_people.Id = id;
            return vw_people;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PinURL
        {
            get
            {
                return _PinURL;
            }
            set
            {
                OnPinURLChanging(value);
                ReportPropertyChanging("PinURL");
                _PinURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PinURL");
                OnPinURLChanged();
            }
        }
        private global::System.String _PinURL;
        partial void OnPinURLChanging(global::System.String value);
        partial void OnPinURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Followers
        {
            get
            {
                return _Followers;
            }
            set
            {
                OnFollowersChanging(value);
                ReportPropertyChanging("Followers");
                _Followers = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Followers");
                OnFollowersChanged();
            }
        }
        private global::System.String _Followers;
        partial void OnFollowersChanging(global::System.String value);
        partial void OnFollowersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Likes
        {
            get
            {
                return _Likes;
            }
            set
            {
                OnLikesChanging(value);
                ReportPropertyChanging("Likes");
                _Likes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Likes");
                OnLikesChanged();
            }
        }
        private Nullable<global::System.Int32> _Likes;
        partial void OnLikesChanging(Nullable<global::System.Int32> value);
        partial void OnLikesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pins
        {
            get
            {
                return _Pins;
            }
            set
            {
                OnPinsChanging(value);
                ReportPropertyChanging("Pins");
                _Pins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pins");
                OnPinsChanged();
            }
        }
        private Nullable<global::System.Int32> _Pins;
        partial void OnPinsChanging(Nullable<global::System.Int32> value);
        partial void OnPinsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Following
        {
            get
            {
                return _Following;
            }
            set
            {
                OnFollowingChanging(value);
                ReportPropertyChanging("Following");
                _Following = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Following");
                OnFollowingChanged();
            }
        }
        private Nullable<global::System.Int32> _Following;
        partial void OnFollowingChanging(Nullable<global::System.Int32> value);
        partial void OnFollowingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Board
        {
            get
            {
                return _Board;
            }
            set
            {
                OnBoardChanging(value);
                ReportPropertyChanging("Board");
                _Board = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Board");
                OnBoardChanged();
            }
        }
        private Nullable<global::System.Int32> _Board;
        partial void OnBoardChanging(Nullable<global::System.Int32> value);
        partial void OnBoardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoardURL
        {
            get
            {
                return _BoardURL;
            }
            set
            {
                OnBoardURLChanging(value);
                ReportPropertyChanging("BoardURL");
                _BoardURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BoardURL");
                OnBoardURLChanged();
            }
        }
        private global::System.String _BoardURL;
        partial void OnBoardURLChanging(global::System.String value);
        partial void OnBoardURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoardTitle
        {
            get
            {
                return _BoardTitle;
            }
            set
            {
                OnBoardTitleChanging(value);
                ReportPropertyChanging("BoardTitle");
                _BoardTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BoardTitle");
                OnBoardTitleChanged();
            }
        }
        private global::System.String _BoardTitle;
        partial void OnBoardTitleChanging(global::System.String value);
        partial void OnBoardTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoardFollowers
        {
            get
            {
                return _BoardFollowers;
            }
            set
            {
                OnBoardFollowersChanging(value);
                ReportPropertyChanging("BoardFollowers");
                _BoardFollowers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BoardFollowers");
                OnBoardFollowersChanged();
            }
        }
        private Nullable<global::System.Int32> _BoardFollowers;
        partial void OnBoardFollowersChanging(Nullable<global::System.Int32> value);
        partial void OnBoardFollowersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoardPins
        {
            get
            {
                return _BoardPins;
            }
            set
            {
                OnBoardPinsChanging(value);
                ReportPropertyChanging("BoardPins");
                _BoardPins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BoardPins");
                OnBoardPinsChanged();
            }
        }
        private Nullable<global::System.Int32> _BoardPins;
        partial void OnBoardPinsChanging(Nullable<global::System.Int32> value);
        partial void OnBoardPinsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
    }

    #endregion

    
}
